### ISSUE TITLE
Consider go.mod dependency management

### ISSUE THREAD

**Issue by johncosta** [stevepartridge/geocodio#5]
Would you consider the introduction of go.mod package management to this project?  

More info about go.mod can be found here: https://blog.golang.org/using-go-modules

I'd be willing to attempt a PR for it if this is something of interest.

**Comment by stevepartridge** [comment]
Thanks for the heads up.  I've added a go.mod file for module reference and cut a [new release](https://github.com/stevepartridge/geocodio/releases/tag/0.2.0).  It also includes support for v1.4

Something to note, currently the package does not require any external dependencies so it should work from Go ~1.9+.

**Comment by johncosta** [comment]
thanks!
