### ISSUE TITLE
Passing additional parameters and fixing batch requests

### ISSUE THREAD

**Issue by robarchibald** [stevepartridge/geocodio#8]
Thanks for your work on this package! It's been helpful for me to get up to speed on the Geocod.io API quickly. 

I'm wondering if you'd be open to a PR which adds the ability to send individual address parts rather than single address string. If so, I can work on a PR for you to consider 

In addition, it looks like the support for batch processing doesn't work quite right. The resulting `geocodio.GeocodeResult` is not quite the right object. Instead, I think there should be a `GeocodeBatchResult` object or something similar which is returned. As it is today, the results are not filling properly.

**Comment by stevepartridge** [comment]
This is great, thank you.  Closing with the merge of #9
